config/routes.rb
Rails.application.routes.draw do

  get 'appointments/index'

  get 'static_pages/home', to: "static_pages#home"
  get '/react',       to:      'react#home'
  get '/react/campaigns',       to:      'react#campaigns'

  get '/login',      to: 'static_pages#index'
  post   '/login',   to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'

  get '/reference',   to: 'reference#show'



  resources :users do

  end

  resources :campaigns do
    member do
      patch :add_user
      get :search_user
      patch :remove_user
    end

    post '/appointments/create', to: 'appointments#create'
    resources :appointments

    resources :pcharacters
    resources :posts
  end

  resources :pcharacters


  root "static_pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :campaign
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :organizers
  has_many :users, :through => :organizers
  has_many :pcharacters
  has_many :appointments
  has_many :posts

  validates :title, presence: true,
                    uniqueness: true

  validates :description, presence: true

end

app/models/organizer.rb
class Organizer < ApplicationRecord
  belongs_to :user
  belongs_to :campaign

  scope :owned, ->{where(dm: true)}

  
end

app/models/pcharacter.rb
class Pcharacter < ApplicationRecord
  belongs_to :user 
  belongs_to :campaign

  has_attached_file :image, styles:{ small: "64x64", 
                                    medium:"400x400",
                                    sheet: "450x800",
                                    large: "800x800" }

  validates_attachment_content_type :image, :content_type => ["image/jpg", 
                                     "image/jpeg", "image/png", "image/gif"]


  validates_presence_of :user, :campaign, :name, 
                        :dnd_race, :dnd_class

  validates_numericality_of :str, :dex, :con, 
                            :wis, :int, :cha,  
                            less_than: 25, greater_than: 0
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :campaign

  validates :title, presence: true
  validates :user_id, presence: true
  validates :campaign_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :organizers
  has_many :campaigns, :through => :organizers
  has_many :pcharacters
  has_many :posts

  validates :screen_name, presence: true, length: { maximum: 30 },
                          uniqueness: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }

  def self.search(search)
    where("screen_name LIKE ? ","%#{search}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @campaign = Campaign.find(params[:campaign_id])

  end

  def new
    @campaign = Campaign.find(params[:campaign_id])
  end

  def destroy
    @post.destroy
    flash[:success] = "Deleted!"
    redirect_to campaign_path(@campaign)

end

app/controllers/react_controller.rb
class ReactController < ApplicationController

  def home
  end

  def campaigns
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show, :index]

  def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search])
    end
    respond_to do |format|
      format.html
      format.json {
        render json: @users
      }
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json {
        render json: @user
      }
    end
  end

  def create
    @user = User.new(user_params)
    @users = User.all
    @user.permission = 1;
    if @user.save
      flash[:success] = 'Welcome to Dragon Binder!'
      DragonMailer.with(user: @user).welcome_email.deliver_now
      log_in @user
      redirect_to user_path(@user)
    else
      flash_error(@user)
      render action: "new"
    end
    respond_to do |format|
      format.html
      format.json {
        render json: @user
      }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated!"
      redirect_to @user
    else
      flash[:danger] = "Failed to create account :< #{@user.errors.full_messages}"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url
  end



  private

    def user_params
      allowed = [:screen_name, :password, :password_confirmation,
                                    :email]

      if is_admin?
       allowed << :permission
      end
      params.require(:user).permit(allowed)
    end

end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController

app/helpers/application_helper.rb
module ApplicationHelper

  def log_in(user = nil)
    if(user)
      session[:user_id] = user.id
    end
  end

  def has_character?(campaign_id)
    current_user.pcharacters.where(campaign_id: campaign_id).present?
  end
  
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def link_to_character_create(campaign)
    if !has_character?(@campaign)
        "<div class='small_box'>
          <a data-toggle='modal' 
          data-target='#new_character_modal'>
          Create a New Character!
          </button>
        </div>".html_safe
    end
  end

  def link_to_character_image(character)
    if character.image.present?
      "<img src='#{character.image(:small)}'/>".html_safe
    end
  end
  
  def link_to_character_controls(character)
    if owns_character?(character)
      link_to 'delete', character, method: :delete
    end
  end

private 

  def owns_character?(character)
    current_user.id == character.user_id
  end

  def has_character?(campaign_id)
    current_user.pcharacters.where(campaign_id: campaign_id).present?
  end

end

app/helpers/characters_helper.rb
module CharactersHelper

end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/react_helper.rb
module ReactHelper
end

app/helpers/reference_helper.rb
module ReferenceHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user = nil)
    if(user)
      session[:user_id] = user.id
    end
  end

  def log_in_with_token()
    AuthorizeApiRequest(request.headers)

  end

  def current_user
    @current_user ||= found_user
  end

  def found_user
    if(session[:user_id])
      User.find_by(id: session[:user_id])
    elsif(request.headers['Authorization'].present?)
      AuthorizeApiRequest.new(request.headers).user
    end
  end


  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_post_feed.haml
- @campaign.posts.each do | post |
  %div{:id => "post_#{post.id}"}
    %h4= post.title
    %p= post.body
    %em= User.find(post.user_id).screen_name

app/views/posts/index.haml
%h2
  = @campaign.title
  posts index

app/views/posts/new.haml
%h2
  = @campaign.title
  New Post

.container-fluid
  .row
    .col-sm-3#small_gray_box
      =form_with scope: :post, local: true do |form|

app/views/users/_results.haml
- @users.each do |user|
  %div{id:"user_#{user.id}"}
    = user.screen_name

    = form_tag(add_user_campaign_path(@campaign), :method => "patch", remote: true) do
      = hidden_field_tag :user_id, user.id
      = submit_tag "Add user", class: "btn btn-primary", :name => nil

app/views/users/_user_feed.haml
.col-sm-8
  - @user.campaigns.each do |campaign|
    %div{:class => "#{is_dm?(campaign.id) ? 'feed_item_special':'feed_item'}"}
      = link_to campaign.title, campaign
      -if is_dm?(campaign.id)
        %em= link_to '**DM Page**', edit_campaign_path(campaign)
      %p= campaign.description

app/views/users/edit.haml
- provide(:title, "Edit User")
%body
  .header
    %h1 Update User
  .container-fluid
    .row
      .col-sm-3#user_display
        %div{:align => "right" }
          = form_for(@user) do |f|
            = f.label :email
            = f.email_field :email
            %br/
            = f.label :password
            = f.password_field :password
            %br/
            = f.label :password_confirmation
            = f.password_field :password_confirmation
            %br/
            - if is_admin?
              = f.label :permission
              =f.select :permission, [["user", 1],["super user", 2],["admin", 3]]
              %br/
            = f.submit "Save changes", class: "btn btn-primary"

app/views/users/index.haml
.header
  %h1 Users Index
  %div
    %table#index_table
      %tr
        %th User
        %th email
        %th permission
        %th
      - @users.each do |user|
        %tr
          %td= link_to user.screen_name, user
          %td= user.email
          %td= user.permission
          %td= link_to 'edit', edit_user_path(user)
          %td= link_to 'delete', user_path(user), method: :delete   

app/views/users/new.haml
.header
  %h1 Sign Up
.wrapper
  %div 
    = render 'shared/signup_form'

app/views/users/search.js.erb
$(".results").html('<%= j(render partial: "users/results") %>');

app/views/users/show.haml
!!!
%html
  %head
    %title Dragon Binder
  %body
    .header
      %h1= @user.screen_name
    .container-fluid
      .row
        .col-sm-3#user_display
          %em you are logged in
          =link_to "Log Out", logout_path, method: :delete
          %br/
          =link_to "New Campaign?", url_for(controller:"campaigns", action: "new")
              
        -if @user.campaigns.any?
          =render partial: 'users/user_feed'