config/routes.rb
Rails.application.routes.draw do

  get 'appointments/index'

  get 'static_pages/home', to: "static_pages#home"
  get '/react',       to:      'react#home'
  get '/react/campaigns',       to:      'react#campaigns'

  get '/login',      to: 'static_pages#index'
  post   '/login',   to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'

  get '/reference',   to: 'reference#show'



  resources :users do

  end

  resources :campaigns do
    member do
      patch :add_user
      get :search_user
      patch :remove_user
    end

    post '/appointments/create', to: 'appointments#create'
    resources :appointments

    resources :pcharacters
    resources :posts
  end

  resources :pcharacters


  root "static_pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :organizers
  has_many :users, :through => :organizers
  has_many :pcharacters
  has_many :appointments
  has_many :posts

  validates :title, presence: true,
                    uniqueness: true

  validates :description, presence: true

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :logged_in_user
  before_action  :is_owner, only:[:edit]

  def index
    render json: Campaign.all
  end

  def new
    @campaign = Campaign.new
  end

  def create

    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      current_user.organizers.create(campaign_id: @campaign.id, dm: true)
      flash[:success] = 'Campaign created!'
      redirect_to @campaign
    else
      flash_error(@campaign)
      render :new
    end
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
  end

  def show
    puts("show")
    @campaign = Campaign.find(params[:id])
    @character = Pcharacter.new
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])
    @user = User.find(params[:id])
    if @campaign.update_attributes(campaign_params)
      flash[:succes]="Campaign Updated"
      redirect_to edit_campaign_path(@campaign)
    else
      flash[:danger]="failed :<"
      render 'edit'
    end
  end

  def search_user
    @campaign = Campaign.find(params[:id])
    @users = User.search(params[:search])
    respond_to do |format|
      format.js { render template: "users/search"}
    end
  end

  def add_user
    @campaign = Campaign.find(params[:id])
    @user = User.find(params[:user_id])

    DragonMailer.with(user: @user, campaign: @campaign).welcome_to_campaign.deliver_now

    @campaign.organizers.create(user_id: @user.id)
  end

  def remove_user
    @campaign = Campaign.find(params[:id])
    @user = User.find(params[:user_id])

    @organizer = @campaign.organizers.where(:user_id => @user.id).first

    @organizer.destroy

    redirect_to edit_campaign_path(@campaign)
  end



  private
    def campaign_params
      params.require(:campaign).permit(:title, :description)
    end

    def is_owner
      @campaign = Campaign.find(params[:id])
      unless is_dm?(@campaign)
        flash[:danger]="access denied"
        redirect_to campaign_path(@campaign)
      end
    end

    def json_request?
      request.format.symbol == :json
    end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def link_to_character_create(campaign)
    if !has_character?(@campaign)
        "<div class='small_box'>
          <a data-toggle='modal' 
          data-target='#new_character_modal'>
          Create a New Character!
          </button>
        </div>".html_safe
    end
  end

  def link_to_character_image(character)
    if character.image.present?
      "<img src='#{character.image(:small)}'/>".html_safe
    end
  end
  
  def link_to_character_controls(character)
    if owns_character?(character)
      link_to 'delete', character, method: :delete
    end
  end

private 

  def owns_character?(character)
    current_user.id == character.user_id
  end

  def has_character?(campaign_id)
    current_user.pcharacters.where(campaign_id: campaign_id).present?
  end

end

app/views/campaigns/_active_user.haml
=link_to user.screen_name, user_path(user)
|
=link_to 'remove', remove_user_campaign_url(@campaign, user_id: user.id), :method => "patch", remote: true
%br

app/views/campaigns/_character_crud.haml
=link_to 'delete', character, method: :delete
=link_to 'edit', pcharacters_edit_path(character)

app/views/campaigns/_character_feed.haml
.col-sm-3
  - @campaign.pcharacters.each do | character |
    .feed_item
      %div{:id => "character_#{character.id}"}
        %h4= character.name
        :javascript
          race = #{character.dnd_race}
          klass = #{character.dnd_class}
          id = #{character.id}
          callRace(race, id)
          callKlass(klass, id)
      =link_to_character_image(character)
      =render "shared/character_stats", :locals =>{:character => character }
      %br
      %em= character.user.screen_name

      %em=link_to_character_controls(character)

app/views/campaigns/_feed_character.haml
%h4= character.name
-if character.image.present?
  %img{:src => "#{character.image(:small)}"}
%em= character.user.screen_name
= link_to 'delete', character, method: :delete

app/views/campaigns/add_user.js.erb
$("#user_<%= @user.id%>").remove();
$(".active_players").append('<%= j(render partial: 'campaigns/active_user', locals: {user:@user}) %>');

app/views/campaigns/edit.haml
.header
  %h1
    DM's Page //
    =@campaign.title

.container-fluid
  .row
    .col-sm-3
      #user_display
        = link_to 'Campaign Home', campaign_path(@campaign)
        %br
        %em PLAYERS:
        .active_players
          =render partial: 'campaigns/active_user', collection: @campaign.users, as: :user 
        %h5 ADD PLAYER
        = render 'shared/search_player_form'
      .small_box
        = render 'shared/edit_campaign_name'
    .col-sm-6
      .small_gray_box
        =render partial: 'shared/email_form'

app/views/campaigns/index.html.haml
%h1 Campaigns#index
%p Find me in app/views/campaigns/index.html.haml

app/views/campaigns/new.haml
.header
  %h1 New Campaign!
  .container-fluid
    .row
      .col-sm-3#user_display
        %div{:align => "right"}
          = render 'shared/new_campaign_form'

app/views/campaigns/show.html.haml
.header
  %h1
    =@campaign.title
.container-fluid
  =render partial: 'shared/new_character_modal'
  .row
    .col-sm-3
      #user_display
        %em= @campaign.description
        %br
        %em USERS:
        .active_players
          - @campaign.users.each do |user|
            =link_to user.screen_name, user_path(user)
            |
        -if is_dm?(@campaign)
          %br
          =link_to 'DM Controls', edit_campaign_path(@campaign)
          =link_to 'Calender', campaign_appointments_path(@campaign)

      =link_to_character_create(@campaign)
    .col-sm-6
      -if @campaign.posts.any?
        =render partial: 'posts/post_feed'
    .col-sm-3.pull-left
      %h4 New Post
      %p new post form to go here
  .row
    -if @campaign.pcharacters.any?
      =render partial: 'campaigns/character_feed'