config/routes.rb
Rails.application.routes.draw do

  get 'appointments/index'

  get 'static_pages/home', to: "static_pages#home"
  get '/react',       to:      'react#home'
  get '/react/campaigns',       to:      'react#campaigns'

  get '/login',      to: 'static_pages#index'
  post   '/login',   to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'

  get '/reference',   to: 'reference#show'



  resources :users do

  end

  resources :campaigns do
    member do
      patch :add_user
      get :search_user
      patch :remove_user
    end

    post '/appointments/create', to: 'appointments#create'
    resources :appointments

    resources :pcharacters
    resources :posts
  end

  resources :pcharacters


  root "static_pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :campaign
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :organizers
  has_many :users, :through => :organizers
  has_many :pcharacters
  has_many :appointments
  has_many :posts

  validates :title, presence: true,
                    uniqueness: true

  validates :description, presence: true

end

app/models/organizer.rb
class Organizer < ApplicationRecord
  belongs_to :user
  belongs_to :campaign

  scope :owned, ->{where(dm: true)}

  
end

app/models/pcharacter.rb
class Pcharacter < ApplicationRecord
  belongs_to :user 
  belongs_to :campaign

  has_attached_file :image, styles:{ small: "64x64", 
                                    medium:"400x400",
                                    sheet: "450x800",
                                    large: "800x800" }

  validates_attachment_content_type :image, :content_type => ["image/jpg", 
                                     "image/jpeg", "image/png", "image/gif"]


  validates_presence_of :user, :campaign, :name, 
                        :dnd_race, :dnd_class

  validates_numericality_of :str, :dex, :con, 
                            :wis, :int, :cha,  
                            less_than: 25, greater_than: 0
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :campaign

  validates :title, presence: true
  validates :user_id, presence: true
  validates :campaign_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :organizers
  has_many :campaigns, :through => :organizers
  has_many :pcharacters
  has_many :posts

  validates :screen_name, presence: true, length: { maximum: 30 },
                          uniqueness: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }

  def self.search(search)
    where("screen_name LIKE ? ","%#{search}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @campaign = Campaign.find(params[:campaign_id])

  end

  def new
    @campaign = Campaign.find(params[:campaign_id])
  end

  def destroy
    @post.destroy
    flash[:success] = "Deleted!"
    redirect_to campaign_path(@campaign)

end

app/helpers/application_helper.rb
module ApplicationHelper

  def log_in(user = nil)
    if(user)
      session[:user_id] = user.id
    end
  end

  def has_character?(campaign_id)
    current_user.pcharacters.where(campaign_id: campaign_id).present?
  end
  
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def link_to_character_create(campaign)
    if !has_character?(@campaign)
        "<div class='small_box'>
          <a data-toggle='modal' 
          data-target='#new_character_modal'>
          Create a New Character!
          </button>
        </div>".html_safe
    end
  end

  def link_to_character_image(character)
    if character.image.present?
      "<img src='#{character.image(:small)}'/>".html_safe
    end
  end
  
  def link_to_character_controls(character)
    if owns_character?(character)
      link_to 'delete', character, method: :delete
    end
  end

private 

  def owns_character?(character)
    current_user.id == character.user_id
  end

  def has_character?(campaign_id)
    current_user.pcharacters.where(campaign_id: campaign_id).present?
  end

end

app/helpers/characters_helper.rb
module CharactersHelper

end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/react_helper.rb
module ReactHelper
end

app/helpers/reference_helper.rb
module ReferenceHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user = nil)
    if(user)
      session[:user_id] = user.id
    end
  end

  def log_in_with_token()
    AuthorizeApiRequest(request.headers)

  end

  def current_user
    @current_user ||= found_user
  end

  def found_user
    if(session[:user_id])
      User.find_by(id: session[:user_id])
    elsif(request.headers['Authorization'].present?)
      AuthorizeApiRequest.new(request.headers).user
    end
  end


  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DragonApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
    <header>
      <%= link_to "Home", root_path %>
      |
      <%= link_to current_user.screen_name, current_user %>
      |
      <%= link_to 'Log Out', logout_path, method: :delete %>
    </header>
    <% end %>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%=(message_type)%>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_character_stats.haml
%em STR
=locals[:character].str
|
%em DEX
=locals[:character].dex
|
%em CON
=locals[:character].con
|
%br
%em WIS
=locals[:character].wis
|
%em INT
=locals[:character].int
|
%em CHA
=locals[:character].cha

app/views/shared/_edit_campaign_name.haml
= form_for(@campaign) do |form| 
  = form.label :title 
  %br
  = form.text_field :title
  %br/
  = form.label :description
  %br
  = form.text_area :description
  %br/
  = form.submit "Update!", class: "btn btn-primary"

app/views/shared/_email_form.haml
%em email form here

app/views/shared/_new_campaign_form.haml
= form_for(@campaign) do |form| 
  = form.label :title 
  = form.text_field :title
  %br/
  = form.label :description
  = form.text_area :description
  %br/
  = form.submit "Create!", class: "btn btn-primary"

app/views/shared/_new_character_form.haml
= form_with(model: [ @campaign, Pcharacter.new ], local: true) do |form|
  = form.label :name 
  %br
  = form.text_field :name
  -if is_dm?(@campaign.id)
    = form.select :user,
       options_from_collection_for_select(@campaign.users, 'id', 'screen_name')
  %br
  = form.label :race
  = form.select :dnd_race, [["Dwarf", 1],["Elf", 2],["Halfling", 3],
                            ["Human", 4],["Dragonborn", 5],["Gnome",6],
                            ["Half-Elf", 7],["Half-Orc", 8],["Tiefling",9] ]
  %br
  = form.label :class
  = form.select :dnd_class, [["Barbarian", 1],["Bard", 2],["Cleric", 3],
                          ["Druid",4], ["Fighter", 5], ["Monk", 6],
                          ["Paladin", 7], ["Ranger", 8], ["Rogue", 9],
                          ["Sorcerer", 10], ["Warlock", 11], ["Wizard", 12] ]
  %br
  = form.label :icon
  = form.file_field :image, class: 'form-control'

  %br
  = form.label :STR
  = form.number_field :str, :max => 18, :min => 4 
  = form.label :DEX
  = form.number_field :dex, :max => 18, :min => 4 
  = form.label :CON
  = form.number_field :con, :max => 18, :min => 4 
  %br
  = form.label :WIS
  = form.number_field :wis, :max => 18, :min => 4
  = form.label :INT
  = form.number_field :int, :max => 18, :min => 4 
  = form.label :CHA
  = form.number_field :cha, :max => 18, :min => 4
  %br
  %br 
  = form.submit "Create!", class: "btn btn-primary"

app/views/shared/_new_character_modal.haml
.modal#new_character_modal
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        .modal-title
          %h2 New Character
      .modal-body
        =render partial: 'shared/new_character_form'

app/views/shared/_search_player_form.haml
= form_tag(search_user_campaign_path(@campaign), :method => "get", remote: true) do
  = text_field_tag :search, params[:search], placeholder: "Search Users by Screen Name"
  = submit_tag "Search", :name => nil

.results

app/views/shared/_signin_form.haml
= form_for(:session, url: login_path) do |form|
  = form.label :screen_name
  = form.text_field :screen_name
  %br/
  %br/
  = form.label :password
  = form.password_field :password
  %br/
  %br/
  = form.submit "Log In", class: "btn btn-primary"
%p
  New User?
  %br/
  = link_to "Sign Up!", new_user_path

app/views/shared/_signup_form.haml
= form_for(@user) do  |form| 
  = form.label :screen_name 
  %br/
  = form.text_field :screen_name
  %br/
  %br/
  =form.label :email
  %br/
  =form.email_field :email
  %br/
  %br/
  = form.label :password
  %br/
  = form.password_field :password
  %br/
  %br/
  = form.label :password_confirmation, "Confirm Password"
  %br/
  = form.password_field :password_confirmation
  %br/
  %br/

  = form.submit "Create Account!"

app/views/shared/search_results.haml
%em= @user.email 